---
title: "Ana"
author: "Sander"
date: "23 May 2018"
output: html_document
---
```{r Clean enviroment}
rm(list = ls())
```

```{r Libraries}
library(googlesheets)
library(arsenal)
library(lubridate)
library(tidyverse)
```

```{r import data}
title <- gs_title(x = "Stierkikker formulieren (Reacties)", verbose = TRUE)
#♠Token <- gs_auth()
#gs_auth(token = Token)
gdrive <- gs_read(title, col_types = cols(`Vijver - Andere` = col_character(),
                                          `Fuik 7 - M1` = col_integer(),
                                          `Fuik 8 - M1` = col_integer(),
                                          `Fuik 9 - L00` = col_integer(),
                                          `Fuik 10 - L00` = col_integer(),
                                          `Fuik 11 - L00` = col_integer(),
                                          `Fuik 8 - M2` = col_integer(),
                                          `Fuik 9 - L2` = col_integer(),
                                          `Fuik 9 - M2` = col_integer(),
                                          `Fuik 10 - Bijvangst [Soort]` = col_character(),
                                          `Fuik 11 - Bijvangst [Soort]` = col_character(),
                                          `Fuik 12 - Bijvangst [Soort]` = col_character()))

SKData <- gdrive

```

```{r Juiste datatypes instellen}
#Datums:
SKData <- SKData %>% 
  mutate(Datum = dmy(Datum))

max(SKData$Datum, na.rm = TRUE)

#Fuik 1
SKData$`Fuik 1 - L00` <- as.numeric(SKData$`Fuik 1 - L00`)
SKData$`Fuik 1 - L0` <- as.numeric(SKData$`Fuik 1 - L0`)
SKData$`Fuik 1 - L1` <- as.numeric(SKData$`Fuik 1 - L1`)
SKData$`Fuik 1 - L2` <- as.numeric(SKData$`Fuik 1 - L2`)
SKData$`Fuik 1 - M1` <- as.numeric(SKData$`Fuik 1 - M1`)
SKData$`Fuik 1 - M2` <- as.numeric(SKData$`Fuik 1 - M2`)
SKData$`Fuik 1 - AM` <- as.numeric(SKData$`Fuik 1 - AM`)
SKData$`Fuik 1 - AV` <- as.numeric(SKData$`Fuik 1 - AV`)
#Fuik 2
SKData$`Fuik 2 - L00` <- as.numeric(SKData$`Fuik 2 - L00`)
SKData$`Fuik 2 - L0` <- as.numeric(SKData$`Fuik 2 - L0`)
SKData$`Fuik 2 - L1` <- as.numeric(SKData$`Fuik 2 - L1`)
SKData$`Fuik 2 - L2` <- as.numeric(SKData$`Fuik 2 - L2`)
SKData$`Fuik 2 - M1` <- as.numeric(SKData$`Fuik 2 - M1`)
SKData$`Fuik 2 - M2` <- as.numeric(SKData$`Fuik 2 - M2`)
SKData$`Fuik 2 - AM` <- as.numeric(SKData$`Fuik 2 - AM`)
SKData$`Fuik 2 - AV` <- as.numeric(SKData$`Fuik 2 - AV`)
#Fuik 3
SKData$`Fuik 3 - L00` <- as.numeric(SKData$`Fuik 3 - L00`)
SKData$`Fuik 3 - L0` <- as.numeric(SKData$`Fuik 3 - L0`)
SKData$`Fuik 3 - L1` <- as.numeric(SKData$`Fuik 3 - L1`)
SKData$`Fuik 3 - L2` <- as.numeric(SKData$`Fuik 3 - L2`)
SKData$`Fuik 3 - M1` <- as.numeric(SKData$`Fuik 3 - M1`)
SKData$`Fuik 3 - M2` <- as.numeric(SKData$`Fuik 3 - M2`)
SKData$`Fuik 3 - AM` <- as.numeric(SKData$`Fuik 3 - AM`)
SKData$`Fuik 3 - AV` <- as.numeric(SKData$`Fuik 3 - AV`)
#Fuik 4
SKData$`Fuik 4 - L00` <- as.numeric(SKData$`Fuik 4 - L00`)
SKData$`Fuik 4 - L0` <- as.numeric(SKData$`Fuik 4 - L0`)
SKData$`Fuik 4 - L1` <- as.numeric(SKData$`Fuik 4 - L1`)
SKData$`Fuik 4 - L2` <- as.numeric(SKData$`Fuik 4 - L2`)
SKData$`Fuik 4 - M1` <- as.numeric(SKData$`Fuik 4 - M1`)
SKData$`Fuik 4 - M2` <- as.numeric(SKData$`Fuik 4 - M2`)
SKData$`Fuik 4 - AM` <- as.numeric(SKData$`Fuik 4 - AM`)
SKData$`Fuik 4 - AV` <- as.numeric(SKData$`Fuik 4 - AV`)
#Fuik 5
SKData$`Fuik 5 - L00` <- as.numeric(SKData$`Fuik 5 - L00`)
SKData$`Fuik 5 - L0` <- as.numeric(SKData$`Fuik 5 - L0`)
SKData$`Fuik 5 - L1` <- as.numeric(SKData$`Fuik 5 - L1`)
SKData$`Fuik 5 - L2` <- as.numeric(SKData$`Fuik 5 - L2`)
SKData$`Fuik 5 - M1` <- as.numeric(SKData$`Fuik 5 - M1`)
SKData$`Fuik 5 - M2` <- as.numeric(SKData$`Fuik 5 - M2`)
SKData$`Fuik 5 - AM` <- as.numeric(SKData$`Fuik 5 - AM`)
SKData$`Fuik 5 - AV` <- as.numeric(SKData$`Fuik 5 - AV`)
#Fuik 6
SKData$`Fuik 6 - L00` <- as.numeric(SKData$`Fuik 6 - L00`)
SKData$`Fuik 6 - L0` <- as.numeric(SKData$`Fuik 6 - L0`)
SKData$`Fuik 6 - L1` <- as.numeric(SKData$`Fuik 6 - L1`)
SKData$`Fuik 6 - L2` <- as.numeric(SKData$`Fuik 6 - L2`)
SKData$`Fuik 6 - M1` <- as.numeric(SKData$`Fuik 6 - M1`)
SKData$`Fuik 6 - M2` <- as.numeric(SKData$`Fuik 6 - M2`)
SKData$`Fuik 6 - AM` <- as.numeric(SKData$`Fuik 6 - AM`)
SKData$`Fuik 6 - AV` <- as.numeric(SKData$`Fuik 6 - AV`)
#Fuik 7
SKData$`Fuik 7 - L00` <- as.numeric(SKData$`Fuik 7 - L00`)
SKData$`Fuik 7 - L0` <- as.numeric(SKData$`Fuik 7 - L0`)
SKData$`Fuik 7 - L1` <- as.numeric(SKData$`Fuik 7 - L1`)
SKData$`Fuik 7 - L2` <- as.numeric(SKData$`Fuik 7 - L2`)
SKData$`Fuik 7 - M1` <- as.numeric(SKData$`Fuik 7 - M1`)
SKData$`Fuik 7 - M2` <- as.numeric(SKData$`Fuik 7 - M2`)
SKData$`Fuik 7 - AM` <- as.numeric(SKData$`Fuik 7 - AM`)
SKData$`Fuik 7 - AV` <- as.numeric(SKData$`Fuik 7 - AV`)
#Fuik 8
SKData$`Fuik 8 - L00` <- as.numeric(SKData$`Fuik 8 - L00`)
SKData$`Fuik 8 - L0` <- as.numeric(SKData$`Fuik 8 - L0`)
SKData$`Fuik 8 - L1` <- as.numeric(SKData$`Fuik 8 - L1`)
SKData$`Fuik 8 - L2` <- as.numeric(SKData$`Fuik 8 - L2`)
SKData$`Fuik 8 - M1` <- as.numeric(SKData$`Fuik 8 - M1`)
SKData$`Fuik 8 - M2` <- as.numeric(SKData$`Fuik 8 - M2`)
SKData$`Fuik 8 - AM` <- as.numeric(SKData$`Fuik 8 - AM`)
SKData$`Fuik 8 - AV` <- as.numeric(SKData$`Fuik 8 - AV`)
#Fuik 9
SKData$`Fuik 9 - L00` <- as.numeric(SKData$`Fuik 9 - L00`)
SKData$`Fuik 9 - L0` <- as.numeric(SKData$`Fuik 9 - L0`)
SKData$`Fuik 9 - L1` <- as.numeric(SKData$`Fuik 9 - L1`)
SKData$`Fuik 9 - L2` <- as.numeric(SKData$`Fuik 9 - L2`)
SKData$`Fuik 9 - M1` <- as.numeric(SKData$`Fuik 9 - M1`)
SKData$`Fuik 9 - M2` <- as.numeric(SKData$`Fuik 9 - M2`)
SKData$`Fuik 9 - AM` <- as.numeric(SKData$`Fuik 9 - AM`)
SKData$`Fuik 9 - AV` <- as.numeric(SKData$`Fuik 9 - AV`)
#Fuik 10
SKData$`Fuik 10 - L00` <- as.numeric(SKData$`Fuik 10 - L00`)
SKData$`Fuik 10 - L0` <- as.numeric(SKData$`Fuik 10 - L0`)
SKData$`Fuik 10 - L1` <- as.numeric(SKData$`Fuik 10 - L1`)
SKData$`Fuik 10 - L2` <- as.numeric(SKData$`Fuik 10 - L2`)
SKData$`Fuik 10 - M1` <- as.numeric(SKData$`Fuik 10 - M1`)
SKData$`Fuik 10 - M2` <- as.numeric(SKData$`Fuik 10 - M2`)
SKData$`Fuik 10 - AM` <- as.numeric(SKData$`Fuik 10 - AM`)
SKData$`Fuik 10 - AV` <- as.numeric(SKData$`Fuik 10 - AV`)
#Fuik 11
SKData$`Fuik 11 - L00` <- as.numeric(SKData$`Fuik 11 - L00`)
SKData$`Fuik 11 - L0` <- as.numeric(SKData$`Fuik 11 - L0`)
SKData$`Fuik 11 - L1` <- as.numeric(SKData$`Fuik 11 - L1`)
SKData$`Fuik 11 - L2` <- as.numeric(SKData$`Fuik 11 - L2`)
SKData$`Fuik 11 - M1` <- as.numeric(SKData$`Fuik 11 - M1`)
SKData$`Fuik 11 - M2` <- as.numeric(SKData$`Fuik 11 - M2`)
SKData$`Fuik 11 - AM` <- as.numeric(SKData$`Fuik 11 - AM`)
SKData$`Fuik 11 - AV` <- as.numeric(SKData$`Fuik 11 - AV`)
#Fuik 12
SKData$`Fuik 12 - L00` <- as.numeric(SKData$`Fuik 12 - L00`)
SKData$`Fuik 12 - L0` <- as.numeric(SKData$`Fuik 12 - L0`)
SKData$`Fuik 12 - L1` <- as.numeric(SKData$`Fuik 12 - L1`)
SKData$`Fuik 12 - L2` <- as.numeric(SKData$`Fuik 12 - L2`)
SKData$`Fuik 12 - M1` <- as.numeric(SKData$`Fuik 12 - M1`)
SKData$`Fuik 12 - M2` <- as.numeric(SKData$`Fuik 12 - M2`)
SKData$`Fuik 12 - AM` <- as.numeric(SKData$`Fuik 12 - AM`)
SKData$`Fuik 12 - AV` <- as.numeric(SKData$`Fuik 12 - AV`)
```


```{r Controle ontbrekende locaties}

#Bekende problemen verwijderen
SKData <- subset(SKData, Tijdstempel != "15-5-2017 23:50:47")
SKData <- subset(SKData, Tijdstempel != "15-5-2017 23:58:58")
SKData <- subset(SKData, Tijdstempel != "15-5-2017 23:45:35")
SKData <- subset(SKData, Tijdstempel != "15-5-2017 23:47:36")
SKData <- subset(SKData, Tijdstempel != "17-5-2017 11:50:04")
SKData <- subset(SKData, Tijdstempel != "17-5-2017 11:56:51")

SKData$`Vijver - Kasterlee` <- ifelse(SKData$`Vijver - Kasterlee`=="retiebaan 1", "Retiebaan 1", 
                                      ifelse(SKData$`Vijver - Kasterlee` =="retiebaan 2", "Retiebaan 2", 
                                             ifelse(SKData$`Vijver - Kasterlee` == "watermolen", "Watermolen", SKData$`Vijver - Kasterlee`)))
SKData$`Vijver - Arendonk` <- ifelse(SKData$`Vijver - Arendonk`== "arendonk 2 b", "Arendonk 2b", SKData$`Vijver - Arendonk`)


SKData <- SKData %>% 
  mutate(Location = case_when(!is.na(`Vijver - Arendonk`) ~ `Vijver - Arendonk`,
                              !is.na(`Vijver - Kasterlee`) ~ `Vijver - Kasterlee`,
                              !is.na(`Vijver - Hoogstraten`) ~ `Vijver - Hoogstraten`,
                              !is.na(`Vijver - Nijlen`) ~ `Vijver - Nijlen`,
                              !is.na(`Vijver - Scheps`) ~ `Vijver - Scheps`,
                              !is.na(`Vijver - Mol`) ~ `Vijver - Mol`,
                              !is.na(`Vijver - Andere`) ~ as.character(`Vijver - Andere`),
                              TRUE ~ as.character(NA)))


SKData$Location <- ifelse(SKData$Tijdstempel == "25-7-2018 8:55:10", "Mol - Tomaathoek", SKData$Location)
SKData$Location <- ifelse(SKData$Tijdstempel == "26-7-2018 9:00:56", "Mol - Tomaathoek", SKData$Location)
SKData$Location <- ifelse(SKData$Tijdstempel == "12-11-2018 12:09:00", "Hoogstraten - Chaamseweg 53", SKData$Location)
SKData$Location <- ifelse(SKData$Tijdstempel == "12-11-2018 18:13:29", "Hoogstraten - Chaamseweg 53", SKData$Location)


table(SKData$Location, useNA = "ifany")
Records_zndr_Location <- subset(SKData, is.na(Location))
Records_met_Location <- subset(SKData, !is.na(Location))

if(nrow(Records_zndr_Location)>0){
  print("Records zonder location gevonden. CONTROLEER ZE !!")
  table(Records_zndr_Location$Tijdstempel, Records_zndr_Location$Locatie, Records_zndr_Location$Invuller)
}
if(nrow(Records_zndr_Location)+nrow(Records_met_Location)==nrow(SKData)){
  print("Datamanipulatie succesvol")
  if(nrow(Records_zndr_Location)>0){
    print(paste(nrow(Records_zndr_Location), "records zonder location verwijderd"))
  }else{
    print("geen records zonder locatie")
    remove(Records_zndr_Location)
  }
}

```

```{r Gekende fouten locaties oplossen}
Records_met_Location2 <- Records_met_Location %>% 
  mutate(Location = case_when(Tijdstempel == "12-6-2019 23:35:26" ~ "Nijlen B10",
                              Tijdstempel == "17-6-2019 21:00:44" ~ "Nijlen B4",
                              TRUE ~ Location))
```

```{r Controle recorders}
temp <- Records_met_Location2

table(temp$`Invuller 2`)
temp$Recorder <- temp$`Invuller 2`

#Bekende problemen oplossen
temp$Recorder <- ifelse(temp$Recorder == "kris meeus", "Kris Meeus", temp$Recorder)
temp$Recorder <- ifelse(temp$Recorder == "pieter liekens", "Pieter Liekens", temp$Recorder)
temp$Recorder <- ifelse(temp$`E-mailadres` == "dries.jonckers@natuurpunt.be" & is.na(temp$Recorder), "Dries Jonckers", temp$Recorder)

temp$Recorder <- ifelse(!is.na(temp$Recorder), temp$Recorder, temp$Invuller)

Records_zndr_Recorder <- subset(temp, is.na(Recorder))
if(nrow(Records_zndr_Recorder)>0){
  print(paste(nrow(Records_zndr_Recorder), " Records zonder recorder, KIJK ZE NA!!", sep=""))
}else{
  print("Geen records zonder recorder")
  remove(Records_zndr_Recorder)
}
table(temp$Recorder, useNA = "ifany")

#Voeg naamloze arbeiders toe
temp <- temp %>% mutate(Recorder2 = case_when(`Aantal werknemers` == 1 ~ Recorder,
                                              `Aantal werknemers` == 2 ~ paste(Recorder, "Arbeider 1", sep =";"),
                                              `Aantal werknemers` == 3 ~ paste(Recorder, "Arbeider 1; Arbeider 2", sep =";"),
                                              `Aantal werknemers` == 4 ~ paste(Recorder, "Arbeider 1; Arbeider 2; Arbeider 3", sep =";"),
                                              `Aantal werknemers` > 5 ~ "NA"))

table(temp$Recorder2)
temp$Recorder <- temp$Recorder2

Records_met_recorders <- temp
remove(temp)
```

```{r Controle missing inputs}
temp <- Records_met_recorders
temp$Sample_Type <- temp$`Wat wil je melden`

#Create vangstdagen op basis van plaatsen van fuiken
temp2 <- subset(temp, Sample_Type == "Plaatsen van Fuiken")
temp2 <- subset(temp2, !is.na(`Start vangstperiode`))
Locations <- unique(temp2$Location)
temp5 <- data.frame(1)
temp6 <- data.frame()

for(l in Locations){
  temp3 <- subset(temp2, Location == l)
  startdagen <- unique(temp3$`Start vangstperiode`)
  for(s in startdagen){
    temp4 <- subset(temp3, `Start vangstperiode` == s)
    temp4$start <- as.numeric(format(as.Date(temp4$`Start vangstperiode`, "%d-%m-%Y"), "%d"))
    temp4$StartMaand <- as.numeric(format(as.Date(temp4$`Start vangstperiode`, "%d-%m-%Y"), "%m"))
    temp4$StartJaar <- as.numeric(format(as.Date(temp4$`Start vangstperiode`, "%d-%m-%Y"), "%Y"))
    temp4$eind <- as.numeric(format(as.Date(temp4$`Eind vangstperiode`, "%d-%m-%Y"), "%d"))
    temp4$aantaldagen <- temp4$eind - temp4$start
    x <- unique(temp4$aantaldagen)
    if(x > 1){
      aantaldagen <- seq(1, x, by = 1)
    }else{
      aantaldagen <- x
    }
    for(y in aantaldagen){
      temp5$Location <- l
      Dag <- unique(temp4$start) + y
      temp5$Datum <- paste(Dag, "-", unique(temp4$StartMaand), "-", unique(temp4$StartJaar), sep="")
      temp6 <- rbind(temp6, temp5)
    }
  }
}

temp6$link <- paste(temp6$Location, temp6$Datum)

#Create vangstdagen op basis van afvangst
temp7 <- subset(temp, Sample_Type == "Afvangst")
temp7$dag <- as.numeric(format(as.Date(temp7$Datum, "%d-%m-%Y"), "%d"))
temp7$maand <- as.numeric(format(as.Date(temp7$Datum, "%d-%m-%Y"), "%m"))
temp7$Jaar <- as.numeric(format(as.Date(temp7$Datum, "%d-%m-%Y"), "%Y"))
temp7$Datum2 <- paste(temp7$dag, "-", temp7$maand, "-", temp7$Jaar, sep="")

temp8 <- temp7[c("Location", "Datum2", "Recorder")]
temp8$link <- paste(temp8$Location, temp8$Datum2)

#Merge Lists
temp9 <- merge(x=temp6, y=temp8, by= "link", all.x = T) 

temp10 <- subset(temp9, is.na(Location.y))

Missing_Inputs <- temp10

remove(temp)
remove(temp2)
remove(temp3)
remove(temp4)
remove(temp5)
remove(temp6)
remove(temp7)
remove(temp8)
remove(temp9)
remove(temp10)

```

```{r Tussentijdse opruim}
temp <- Records_met_recorders
temp$Sample_Type <- temp$`Wat wil je melden`
temp$`Wat wil je melden` <- NULL
temp$`Vijver - Arendonk` <- NULL
temp$`Vijver - Kasterlee` <- NULL
temp$`Vijver - Hoogstraten` <- NULL
temp$`Vijver - Nijlen` <- NULL
temp$`Vijver - Scheps` <- NULL
#temp$Locatie <- NULL
temp$`Gemeente/Deelgemeente` <- NULL
temp$Invuller <- NULL
temp$Recorder2 <- NULL
temp$`Aantal werknemers` <- NULL
temp$`Invuller 2` <- NULL
```

```{r Invullen NAs in aantal fuiken}
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "10-5-2016 20:50:24", 2, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "11-5-2016 22:45:28", 1, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "11-5-2016 22:50:30", 3, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "14-5-2016 12:04:04", 4, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "14-5-2016 12:18:34", 4, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "14-5-2016 12:12:05", 1, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "14-5-2016 12:48:21", 1, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "14-5-2016 12:52:58", 2, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "14-5-2016 12:55:16", 2, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "14-5-2016 12:56:54", 1, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "14-5-2016 12:59:21", 1, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "14-5-2016 13:02:53", 2, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "14-5-2016 13:06:01", 4, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "19-5-2016 0:08:54", 4, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "13-6-2016 22:25:13", 2, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "13-6-2016 22:41:34", 3, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "13-6-2016 22:55:46", 3, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "13-6-2016 22:48:47", 4, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "13-6-2016 23:00:13", 4, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "13-6-2016 23:15:32", 2, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "13-6-2016 23:17:03", 1, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "13-6-2016 23:19:12", 3, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "13-6-2016 23:21:17", 3, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "23-5-2018 15:50:10", 3.5, temp$`Aantal fuiken (Totaal)`)
temp$`Aantal fuiken (Totaal)` <- ifelse(temp$Tijdstempel == "17-1-2019 21:58:04", 2, temp$`Aantal fuiken (Totaal)`)

test <- subset(temp, Sample_Type == "Afvangst")
test <- subset(test, is.na(`Aantal fuiken (Totaal)`))
if(nrow(test)==0){
  remove(test)
}else{
  print("Er ontbreken fuiken, controleer ze !!")
}
Records_met_fuiken <- temp
remove(temp)
```

```{r}
temp <- Records_met_fuiken %>%
  mutate(Sample_Type = case_when(Tijdstempel == "9-8-2016 23:49:54" ~ "Afvangst_BSF",
                                 Tijdstempel == "9-8-2016 23:51:44" ~ "Afvangst_DSF",
                                 Tijdstempel == "9-8-2016 23:34:23" ~ "Afvangst_BSF",
                                 Tijdstempel == "9-8-2016 23:35:49" ~ "Afvangst_DSF",
                                 TRUE ~ Sample_Type))

if(nrow(temp) == nrow(Records_met_fuiken)){
  Records_met_fuiken <- temp
}
```


```{r Datums corrigeren}
temp <- Records_met_fuiken
#Bekende problemen oplossen 
#Voornamelijk dubbele datums
temp <- subset(temp, Tijdstempel != "14-5-2016 13:06:01")
temp <- subset(temp, Tijdstempel != "9-8-2016 23:58:14")
temp <- subset(temp, Tijdstempel != "26-10-2016 20:16:52")
temp <- subset(temp, Tijdstempel != "26-10-2016 20:18:19")
temp <- subset(temp, Tijdstempel != "26-10-2016 20:19:35")
temp <- subset(temp, Tijdstempel != "17-5-2017 23:21:58")
temp <- subset(temp, Tijdstempel != "17-5-2017 23:28:57")
temp <- subset(temp, Tijdstempel != "6-6-2017 17:18:18")
temp <- subset(temp, Tijdstempel != "6-6-2017 17:13:07")
print(paste(nrow(Records_met_fuiken)-nrow(temp), "Records verwijderd"))

#NA datums verwijderen

temp <- temp %>% 
  mutate(Datum = case_when(Tijdstempel == "22-6-2017 21:47:39" ~ dmy("20-6-2017"),
                           Tijdstempel == "9-10-2017 22:46:06" ~ dmy("27-9-2017"),
                           Tijdstempel == "24-8-2018 12:32:26" ~ dmy("14-8-2018"),
                           TRUE ~ Datum ))

NA_Datums <- subset(temp, is.na(Datum))

if(nrow(NA_Datums)>0){
  print(paste(nrow(NA_Datums), "NA datums gevonden"))
  temp2 <- subset(temp, !is.na(Datum))
  print(paste(nrow(temp)-nrow(temp2), "Records verwijderd"))
}else{
  print("Geen NA datums")
  remove(NA_Datums)
  temp2 <- temp
}

Records_met_datums <- temp2
remove(temp)
remove(temp2)
```

```{r check for dubbele datums}
dubbele_datums <- Records_met_datums %>%
  group_by(Sample_Type, Datum, Location) %>%
  summarise(n=n()) %>% 
  filter(n>1) %>%
  filter(Sample_Type == "Afvangst")


temp <- Records_met_datums %>% 
  mutate(Datum = case_when(Tijdstempel == "24-8-2018 12:24:04" ~ "11-08-2018",
                           TRUE ~ as.character(Datum))) %>%
  filter(!Tijdstempel %in% c("17-1-2019 21:07:00", "3-9-2018 12:58:51", "3-9-2018 13:24:29", "17-1-2019 22:02:05", "3-9-2018 12:38:53", "3-9-2018 13:19:17", "3-9-2018 13:36:12", "10-9-2018 9:25:49", "10-9-2018 9:44:45", "10-9-2018 9:34:34", "3-9-2018 12:48:53", "3-9-2018 13:01:21", "3-9-2018 13:10:38", "3-9-2018 13:31:10", "3-9-2018 13:08:06", "3-9-2018 13:27:00", "10-9-2018 9:21:24", "10-9-2018 9:28:56"))

dubbele_datums2 <- temp %>%
  mutate(Datum2 = as.Date(Datum, format("%Y-%m-%d"))) %>%
  group_by(Sample_Type, Datum2, Location) %>%
  summarise(n=n()) %>% 
  filter(n>1) %>%
  filter(Sample_Type == "Afvangst")

if(nrow(dubbele_datums)>0){
  print(paste(nrow(dubbele_datums), "dubbele datums gevonden"))
  print(paste(nrow(Records_met_datums)-nrow(temp), "Records verwijderd"))
  if(nrow(dubbele_datums2)>0){
    print(paste(nrow(dubbele_datums2), "dubbele datums over"))
  }else{
    print("alle dubbele datums verwijderd")
    Records_met_datums <- temp
    remove(temp)
    remove(dubbele_datums)
    remove(dubbele_datums2)
  }
}

```

```{r Check for missing jaren}
temp <- Records_met_datums %>% 
  mutate(Jaar = case_when(!is.na(Jaar) ~ Jaar,
                          TRUE ~ year(Datum)))

table(temp$Jaar, useNA = "ifany")

missing_jaar <- temp %>% 
  filter(is.na(Jaar) | Jaar < 2016)

if(nrow(missing_jaar) == 0){
  Records_met_datums <- temp
}else{
  print("Er zijn foutieve jaren, CONTROLEER ZE !!!")
}

```


```{r Delete known errors}

foute_tijdstempels <- c("3-9-2018 13:19:17", "3-9-2018 13:36:12", "10-9-2018 9:44:45", "3-9-2018 12:38:53")

Records_met_datums <- Records_met_datums %>% 
  filter(!Tijdstempel %in% foute_tijdstempels)

```

```{r Check for update}
if(!dir.exists("./Intermediate/")){
  dir.create("./Intermediate/")
  dir.create("./Intermediate/Backup")
  aantal_offline <- 0
}else{
  if(file.exists("./Intermediate/Brondata.csv")){
    data_offline <- read_csv("./Intermediate/Brondata.csv", 
                             col_types = cols("Fuik 10 - Bijvangst [Soort]" = col_character(),
                                              "Fuik 11 - Bijvangst [Soort]" = col_character(),
                                              "Fuik 12 - Bijvangst [Soort]" = col_character(),
                                              "Vijver - Andere" = col_character(),
                                              "Fuik 9 - L00" = col_integer(),
                                              "Fuik 10 - L00" = col_integer(),
                                              "Fuik 11 - L00" = col_integer(),
                                              "Fuik 8 - M2" = col_integer(),
                                              "Fuik 9 - L2" = col_integer(),
                                              "Fuik 9 - M2" = col_integer(),
                                              "Fuik 7 - M1" = col_integer(),
                                              "Fuik 8 - M1" = col_integer()))
  }else{
    data_offline <- data.frame()
  }
  aantal_offline <- nrow(data_offline)
}

aantal_online <- nrow(Records_met_datums)


verschil <- aantal_online - aantal_offline
verschil2 <- diffs(comparedf(Records_met_datums, data_offline))


print(paste(verschil, " nieuwe records", sep=""))
```

```{r Export}
if (verschil != 0){
  if(file.exists("./Intermediate/Brondata.csv")){
    today <- as.Date(Sys.time(), format="%Y%m%d")
    backup <- read_csv("./Intermediate/Brondata.csv", 
                       col_types = cols("Fuik 10 - Bijvangst [Soort]" = col_character(),
                                        "Fuik 11 - Bijvangst [Soort]" = col_character(),
                                        "Fuik 12 - Bijvangst [Soort]" = col_character(),
                                        "Vijver - Andere" = col_character(),
                                        "Fuik 9 - L00" = col_integer(),
                                        "Fuik 10 - L00" = col_integer(),
                                        "Fuik 11 - L00" = col_integer(),
                                        "Fuik 8 - M2" = col_integer(),
                                        "Fuik 9 - L2" = col_integer(),
                                        "Fuik 9 - M2" = col_integer(),
                                        "Fuik 7 - M1" = col_integer(),
                                        "Fuik 8 - M1" = col_integer()))
    fn <- paste("./Intermediate/Backup/Brondata_", today, ".csv", sep="")
    write_csv(backup, fn)
    write_csv(Records_met_datums, "./Intermediate/Brondata.csv")
    print(paste0("Data backed up and exported(", verschil,")"))
  }else{
    write_csv(Records_met_datums, "./Intermediate/Brondata.csv")
    print(paste0("Data exported (", verschil,")"))
  }
}else{
  if(verschil == 0 & nrow(verschil2) > 0){
    write_csv(Records_met_datums, "./Intermediate/Brondata.csv")
    print("Data altered")
  }else{
    print("no new records")
  }  
}



```

