---
title: "Grafieken"
author: "Sander"
date: "23 May 2018"
output: html_document
---

```{r Clean enviroment}
rm(list = ls())
```

```{r Libraries}
library(tidyverse)
library(scales)
#library(ggplot2)
library(INBOtheme)
library(extrafont) #Voor Ravon artikel
theme_set(theme_inbo(base_size = 18))
```

```{r Read data}
Brondata <- read_csv("./Intermediate/Brondata.csv", 
                         col_types = cols("Fuik 10 - Bijvangst [Soort]" = col_character(),
                                          "Fuik 11 - Bijvangst [Soort]" = col_character(),
                                          "Fuik 12 - Bijvangst [Soort]" = col_character(),
                                          "Vijver - Andere" = col_character(),
                                          "Fuik 9 - L00" = col_integer(),
                                          "Fuik 10 - L00" = col_integer(),
                                          "Fuik 11 - L00" = col_integer(),
                                          "Fuik 8 - M2" = col_integer(),
                                          "Fuik 9 - L2" = col_integer(),
                                          "Fuik 9 - M2" = col_integer(),
                                          "Fuik 7 - M1" = col_integer(),
                                          "Fuik 8 - M1" = col_integer()))

#Fuik 1
Brondata$`Fuik 1 - L00` <- as.numeric(Brondata$`Fuik 1 - L00`)
Brondata$`Fuik 1 - L0` <- as.numeric(Brondata$`Fuik 1 - L0`)
Brondata$`Fuik 1 - L1` <- as.numeric(Brondata$`Fuik 1 - L1`)
Brondata$`Fuik 1 - L2` <- as.numeric(Brondata$`Fuik 1 - L2`)
Brondata$`Fuik 1 - M1` <- as.numeric(Brondata$`Fuik 1 - M1`)
Brondata$`Fuik 1 - M2` <- as.numeric(Brondata$`Fuik 1 - M2`)
Brondata$`Fuik 1 - AM` <- as.numeric(Brondata$`Fuik 1 - AM`)
Brondata$`Fuik 1 - AV` <- as.numeric(Brondata$`Fuik 1 - AV`)
#Fuik 2
Brondata$`Fuik 2 - L00` <- as.numeric(Brondata$`Fuik 2 - L00`)
Brondata$`Fuik 2 - L0` <- as.numeric(Brondata$`Fuik 2 - L0`)
Brondata$`Fuik 2 - L1` <- as.numeric(Brondata$`Fuik 2 - L1`)
Brondata$`Fuik 2 - L2` <- as.numeric(Brondata$`Fuik 2 - L2`)
Brondata$`Fuik 2 - M1` <- as.numeric(Brondata$`Fuik 2 - M1`)
Brondata$`Fuik 2 - M2` <- as.numeric(Brondata$`Fuik 2 - M2`)
Brondata$`Fuik 2 - AM` <- as.numeric(Brondata$`Fuik 2 - AM`)
Brondata$`Fuik 2 - AV` <- as.numeric(Brondata$`Fuik 2 - AV`)
#Fuik 3
Brondata$`Fuik 3 - L00` <- as.numeric(Brondata$`Fuik 3 - L00`)
Brondata$`Fuik 3 - L0` <- as.numeric(Brondata$`Fuik 3 - L0`)
Brondata$`Fuik 3 - L1` <- as.numeric(Brondata$`Fuik 3 - L1`)
Brondata$`Fuik 3 - L2` <- as.numeric(Brondata$`Fuik 3 - L2`)
Brondata$`Fuik 3 - M1` <- as.numeric(Brondata$`Fuik 3 - M1`)
Brondata$`Fuik 3 - M2` <- as.numeric(Brondata$`Fuik 3 - M2`)
Brondata$`Fuik 3 - AM` <- as.numeric(Brondata$`Fuik 3 - AM`)
Brondata$`Fuik 3 - AV` <- as.numeric(Brondata$`Fuik 3 - AV`)
#Fuik 4
Brondata$`Fuik 4 - L00` <- as.numeric(Brondata$`Fuik 4 - L00`)
Brondata$`Fuik 4 - L0` <- as.numeric(Brondata$`Fuik 4 - L0`)
Brondata$`Fuik 4 - L1` <- as.numeric(Brondata$`Fuik 4 - L1`)
Brondata$`Fuik 4 - L2` <- as.numeric(Brondata$`Fuik 4 - L2`)
Brondata$`Fuik 4 - M1` <- as.numeric(Brondata$`Fuik 4 - M1`)
Brondata$`Fuik 4 - M2` <- as.numeric(Brondata$`Fuik 4 - M2`)
Brondata$`Fuik 4 - AM` <- as.numeric(Brondata$`Fuik 4 - AM`)
Brondata$`Fuik 4 - AV` <- as.numeric(Brondata$`Fuik 4 - AV`)
#Fuik 5
Brondata$`Fuik 5 - L00` <- as.numeric(Brondata$`Fuik 5 - L00`)
Brondata$`Fuik 5 - L0` <- as.numeric(Brondata$`Fuik 5 - L0`)
Brondata$`Fuik 5 - L1` <- as.numeric(Brondata$`Fuik 5 - L1`)
Brondata$`Fuik 5 - L2` <- as.numeric(Brondata$`Fuik 5 - L2`)
Brondata$`Fuik 5 - M1` <- as.numeric(Brondata$`Fuik 5 - M1`)
Brondata$`Fuik 5 - M2` <- as.numeric(Brondata$`Fuik 5 - M2`)
Brondata$`Fuik 5 - AM` <- as.numeric(Brondata$`Fuik 5 - AM`)
Brondata$`Fuik 5 - AV` <- as.numeric(Brondata$`Fuik 5 - AV`)
#Fuik 6
Brondata$`Fuik 6 - L00` <- as.numeric(Brondata$`Fuik 6 - L00`)
Brondata$`Fuik 6 - L0` <- as.numeric(Brondata$`Fuik 6 - L0`)
Brondata$`Fuik 6 - L1` <- as.numeric(Brondata$`Fuik 6 - L1`)
Brondata$`Fuik 6 - L2` <- as.numeric(Brondata$`Fuik 6 - L2`)
Brondata$`Fuik 6 - M1` <- as.numeric(Brondata$`Fuik 6 - M1`)
Brondata$`Fuik 6 - M2` <- as.numeric(Brondata$`Fuik 6 - M2`)
Brondata$`Fuik 6 - AM` <- as.numeric(Brondata$`Fuik 6 - AM`)
Brondata$`Fuik 6 - AV` <- as.numeric(Brondata$`Fuik 6 - AV`)
#Fuik 7
Brondata$`Fuik 7 - L00` <- as.numeric(Brondata$`Fuik 7 - L00`)
Brondata$`Fuik 7 - L0` <- as.numeric(Brondata$`Fuik 7 - L0`)
Brondata$`Fuik 7 - L1` <- as.numeric(Brondata$`Fuik 7 - L1`)
Brondata$`Fuik 7 - L2` <- as.numeric(Brondata$`Fuik 7 - L2`)
Brondata$`Fuik 7 - M1` <- as.numeric(Brondata$`Fuik 7 - M1`)
Brondata$`Fuik 7 - M2` <- as.numeric(Brondata$`Fuik 7 - M2`)
Brondata$`Fuik 7 - AM` <- as.numeric(Brondata$`Fuik 7 - AM`)
Brondata$`Fuik 7 - AV` <- as.numeric(Brondata$`Fuik 7 - AV`)
#Fuik 8
Brondata$`Fuik 8 - L00` <- as.numeric(Brondata$`Fuik 8 - L00`)
Brondata$`Fuik 8 - L0` <- as.numeric(Brondata$`Fuik 8 - L0`)
Brondata$`Fuik 8 - L1` <- as.numeric(Brondata$`Fuik 8 - L1`)
Brondata$`Fuik 8 - L2` <- as.numeric(Brondata$`Fuik 8 - L2`)
Brondata$`Fuik 8 - M1` <- as.numeric(Brondata$`Fuik 8 - M1`)
Brondata$`Fuik 8 - M2` <- as.numeric(Brondata$`Fuik 8 - M2`)
Brondata$`Fuik 8 - AM` <- as.numeric(Brondata$`Fuik 8 - AM`)
Brondata$`Fuik 8 - AV` <- as.numeric(Brondata$`Fuik 8 - AV`)
#Fuik 9
Brondata$`Fuik 9 - L00` <- as.numeric(Brondata$`Fuik 9 - L00`)
Brondata$`Fuik 9 - L0` <- as.numeric(Brondata$`Fuik 9 - L0`)
Brondata$`Fuik 9 - L1` <- as.numeric(Brondata$`Fuik 9 - L1`)
Brondata$`Fuik 9 - L2` <- as.numeric(Brondata$`Fuik 9 - L2`)
Brondata$`Fuik 9 - M1` <- as.numeric(Brondata$`Fuik 9 - M1`)
Brondata$`Fuik 9 - M2` <- as.numeric(Brondata$`Fuik 9 - M2`)
Brondata$`Fuik 9 - AM` <- as.numeric(Brondata$`Fuik 9 - AM`)
Brondata$`Fuik 9 - AV` <- as.numeric(Brondata$`Fuik 9 - AV`)
#Fuik 10
Brondata$`Fuik 10 - L00` <- as.numeric(Brondata$`Fuik 10 - L00`)
Brondata$`Fuik 10 - L0` <- as.numeric(Brondata$`Fuik 10 - L0`)
Brondata$`Fuik 10 - L1` <- as.numeric(Brondata$`Fuik 10 - L1`)
Brondata$`Fuik 10 - L2` <- as.numeric(Brondata$`Fuik 10 - L2`)
Brondata$`Fuik 10 - M1` <- as.numeric(Brondata$`Fuik 10 - M1`)
Brondata$`Fuik 10 - M2` <- as.numeric(Brondata$`Fuik 10 - M2`)
Brondata$`Fuik 10 - AM` <- as.numeric(Brondata$`Fuik 10 - AM`)
Brondata$`Fuik 10 - AV` <- as.numeric(Brondata$`Fuik 10 - AV`)
#Fuik 11
Brondata$`Fuik 11 - L00` <- as.numeric(Brondata$`Fuik 11 - L00`)
Brondata$`Fuik 11 - L0` <- as.numeric(Brondata$`Fuik 11 - L0`)
Brondata$`Fuik 11 - L1` <- as.numeric(Brondata$`Fuik 11 - L1`)
Brondata$`Fuik 11 - L2` <- as.numeric(Brondata$`Fuik 11 - L2`)
Brondata$`Fuik 11 - M1` <- as.numeric(Brondata$`Fuik 11 - M1`)
Brondata$`Fuik 11 - M2` <- as.numeric(Brondata$`Fuik 11 - M2`)
Brondata$`Fuik 11 - AM` <- as.numeric(Brondata$`Fuik 11 - AM`)
Brondata$`Fuik 11 - AV` <- as.numeric(Brondata$`Fuik 11 - AV`)
#Fuik 12
Brondata$`Fuik 12 - L00` <- as.numeric(Brondata$`Fuik 12 - L00`)
Brondata$`Fuik 12 - L0` <- as.numeric(Brondata$`Fuik 12 - L0`)
Brondata$`Fuik 12 - L1` <- as.numeric(Brondata$`Fuik 12 - L1`)
Brondata$`Fuik 12 - L2` <- as.numeric(Brondata$`Fuik 12 - L2`)
Brondata$`Fuik 12 - M1` <- as.numeric(Brondata$`Fuik 12 - M1`)
Brondata$`Fuik 12 - M2` <- as.numeric(Brondata$`Fuik 12 - M2`)
Brondata$`Fuik 12 - AM` <- as.numeric(Brondata$`Fuik 12 - AM`)
Brondata$`Fuik 12 - AV` <- as.numeric(Brondata$`Fuik 12 - AV`)
```

```{r Subset data}
Afvangsten <- Brondata %>% 
  filter(grepl(pattern = "afvangst", Sample_Type, ignore.case = TRUE),
         !grepl(pattern = "BSF", Sample_Type),
         !grepl(pattern = "DSF", Sample_Type)) %>% 
  mutate(Sample_Type = "Afvangst")

table(Afvangsten$Sample_Type)
```

```{r prep dataframe}
Afvangsten$L00 <- as.numeric(NA)
Afvangsten$L0 <- as.numeric(NA)
Afvangsten$L1 <- as.numeric(NA)
Afvangsten$L2 <- as.numeric(NA)
Afvangsten$M1 <- as.numeric(NA)
Afvangsten$M2 <- as.numeric(NA)
Afvangsten$AM <- as.numeric(NA)
Afvangsten$AV <- as.numeric(NA)
```

```{r Sum of all stage specefic columns}
Afvangsten$L00[!is.na(Afvangsten$`Fuik 1 - L00`)
               |!is.na(Afvangsten$`Fuik 2 - L00`)
               |!is.na(Afvangsten$`Fuik 3 - L00`)
               |!is.na(Afvangsten$`Fuik 4 - L00`)
               |!is.na(Afvangsten$`Fuik 5 - L00`)
               |!is.na(Afvangsten$`Fuik 6 - L00`)
               |!is.na(Afvangsten$`Fuik 7 - L00`)
               |!is.na(Afvangsten$`Fuik 8 - L00`)
               |!is.na(Afvangsten$`Fuik 9 - L00`)
               |!is.na(Afvangsten$`Fuik 10 - L00`)
               |!is.na(Afvangsten$`Fuik 11 - L00`)
               |!is.na(Afvangsten$`Fuik 12 - L00`)] <- 
  rowSums(Afvangsten[!is.na(Afvangsten$`Fuik 1 - L00`)
                     |!is.na(Afvangsten$`Fuik 2 - L00`)
                     |!is.na(Afvangsten$`Fuik 3 - L00`)
                     |!is.na(Afvangsten$`Fuik 4 - L00`)
                     |!is.na(Afvangsten$`Fuik 5 - L00`)
                     |!is.na(Afvangsten$`Fuik 6 - L00`)
                     |!is.na(Afvangsten$`Fuik 7 - L00`)
                     |!is.na(Afvangsten$`Fuik 8 - L00`)
                     |!is.na(Afvangsten$`Fuik 9 - L00`)
                     |!is.na(Afvangsten$`Fuik 10 - L00`)
                     |!is.na(Afvangsten$`Fuik 11 - L00`)
                     |!is.na(Afvangsten$`Fuik 12 - L00`), 
                     c('Fuik 1 - L00', 
                       'Fuik 2 - L00',
                       'Fuik 3 - L00',
                       'Fuik 4 - L00',
                       'Fuik 5 - L00',
                       'Fuik 6 - L00',
                       'Fuik 7 - L00',
                       'Fuik 8 - L00',
                       'Fuik 9 - L00',
                       'Fuik 10 - L00',
                       'Fuik 11 - L00',
                       'Fuik 12 - L00')], 
          na.rm = T)

Afvangsten$L0[!is.na(Afvangsten$`Fuik 1 - L0`)
              |!is.na(Afvangsten$`Fuik 2 - L0`)
              |!is.na(Afvangsten$`Fuik 3 - L0`)
              |!is.na(Afvangsten$`Fuik 4 - L0`)
              |!is.na(Afvangsten$`Fuik 5 - L0`)
              |!is.na(Afvangsten$`Fuik 6 - L0`)
              |!is.na(Afvangsten$`Fuik 7 - L0`)
              |!is.na(Afvangsten$`Fuik 8 - L0`)
              |!is.na(Afvangsten$`Fuik 9 - L0`)
              |!is.na(Afvangsten$`Fuik 10 - L0`)
              |!is.na(Afvangsten$`Fuik 11 - L0`)
              |!is.na(Afvangsten$`Fuik 12 - L0`)] <- 
  rowSums(Afvangsten[!is.na(Afvangsten$`Fuik 1 - L0`)
                     |!is.na(Afvangsten$`Fuik 2 - L0`)
                     |!is.na(Afvangsten$`Fuik 3 - L0`)
                     |!is.na(Afvangsten$`Fuik 4 - L0`)
                     |!is.na(Afvangsten$`Fuik 5 - L0`)
                     |!is.na(Afvangsten$`Fuik 6 - L0`)
                     |!is.na(Afvangsten$`Fuik 7 - L0`)
                     |!is.na(Afvangsten$`Fuik 8 - L0`)
                     |!is.na(Afvangsten$`Fuik 9 - L0`)
                     |!is.na(Afvangsten$`Fuik 10 - L0`)
                     |!is.na(Afvangsten$`Fuik 11 - L0`)
                     |!is.na(Afvangsten$`Fuik 12 - L0`), 
                     c('Fuik 1 - L0', 
                       'Fuik 2 - L0',
                       'Fuik 3 - L0',
                       'Fuik 4 - L0',
                       'Fuik 5 - L0',
                       'Fuik 6 - L0',
                       'Fuik 7 - L0',
                       'Fuik 8 - L0',
                       'Fuik 9 - L0',
                       'Fuik 10 - L0',
                       'Fuik 11 - L0',
                       'Fuik 12 - L0')], 
          na.rm = T)

Afvangsten$L1[!is.na(Afvangsten$`Fuik 1 - L1`)
              |!is.na(Afvangsten$`Fuik 2 - L1`)
              |!is.na(Afvangsten$`Fuik 3 - L1`)
              |!is.na(Afvangsten$`Fuik 4 - L1`)
              |!is.na(Afvangsten$`Fuik 5 - L1`)
              |!is.na(Afvangsten$`Fuik 6 - L1`)
              |!is.na(Afvangsten$`Fuik 7 - L1`)
              |!is.na(Afvangsten$`Fuik 8 - L1`)
              |!is.na(Afvangsten$`Fuik 9 - L1`)
              |!is.na(Afvangsten$`Fuik 10 - L1`)
              |!is.na(Afvangsten$`Fuik 11 - L1`)
              |!is.na(Afvangsten$`Fuik 12 - L1`)] <- 
  rowSums(Afvangsten[!is.na(Afvangsten$`Fuik 1 - L1`)
                     |!is.na(Afvangsten$`Fuik 2 - L1`)
                     |!is.na(Afvangsten$`Fuik 3 - L1`)
                     |!is.na(Afvangsten$`Fuik 4 - L1`)
                     |!is.na(Afvangsten$`Fuik 5 - L1`)
                     |!is.na(Afvangsten$`Fuik 6 - L1`)
                     |!is.na(Afvangsten$`Fuik 7 - L1`)
                     |!is.na(Afvangsten$`Fuik 8 - L1`)
                     |!is.na(Afvangsten$`Fuik 9 - L1`)
                     |!is.na(Afvangsten$`Fuik 10 - L1`)
                     |!is.na(Afvangsten$`Fuik 11 - L1`)
                     |!is.na(Afvangsten$`Fuik 12 - L1`), 
                     c('Fuik 1 - L1', 
                       'Fuik 2 - L1',
                       'Fuik 3 - L1',
                       'Fuik 4 - L1',
                       'Fuik 5 - L1',
                       'Fuik 6 - L1',
                       'Fuik 7 - L1',
                       'Fuik 8 - L1',
                       'Fuik 9 - L1',
                       'Fuik 10 - L1',
                       'Fuik 11 - L1',
                       'Fuik 12 - L1')], 
          na.rm = T)

Afvangsten$L2[!is.na(Afvangsten$`Fuik 1 - L2`)
              |!is.na(Afvangsten$`Fuik 2 - L2`)
              |!is.na(Afvangsten$`Fuik 3 - L2`)
              |!is.na(Afvangsten$`Fuik 4 - L2`)
              |!is.na(Afvangsten$`Fuik 5 - L2`)
              |!is.na(Afvangsten$`Fuik 6 - L2`)
              |!is.na(Afvangsten$`Fuik 7 - L2`)
              |!is.na(Afvangsten$`Fuik 8 - L2`)
              |!is.na(Afvangsten$`Fuik 9 - L2`)
              |!is.na(Afvangsten$`Fuik 10 - L2`)
              |!is.na(Afvangsten$`Fuik 11 - L2`)
              |!is.na(Afvangsten$`Fuik 12 - L2`)] <- 
  rowSums(Afvangsten[!is.na(Afvangsten$`Fuik 1 - L2`)
                     |!is.na(Afvangsten$`Fuik 2 - L2`)
                     |!is.na(Afvangsten$`Fuik 3 - L2`)
                     |!is.na(Afvangsten$`Fuik 4 - L2`)
                     |!is.na(Afvangsten$`Fuik 5 - L2`)
                     |!is.na(Afvangsten$`Fuik 6 - L2`)
                     |!is.na(Afvangsten$`Fuik 7 - L2`)
                     |!is.na(Afvangsten$`Fuik 8 - L2`)
                     |!is.na(Afvangsten$`Fuik 9 - L2`)
                     |!is.na(Afvangsten$`Fuik 10 - L2`)
                     |!is.na(Afvangsten$`Fuik 11 - L2`)
                     |!is.na(Afvangsten$`Fuik 12 - L2`), 
                     c('Fuik 1 - L2', 
                       'Fuik 2 - L2',
                       'Fuik 3 - L2',
                       'Fuik 4 - L2',
                       'Fuik 5 - L2',
                       'Fuik 6 - L2',
                       'Fuik 7 - L2',
                       'Fuik 8 - L2',
                       'Fuik 9 - L2',
                       'Fuik 10 - L2',
                       'Fuik 11 - L2',
                       'Fuik 12 - L2')], 
          na.rm = T)

Afvangsten$M1[!is.na(Afvangsten$`Fuik 1 - M1`)
              |!is.na(Afvangsten$`Fuik 2 - M1`)
              |!is.na(Afvangsten$`Fuik 3 - M1`)
              |!is.na(Afvangsten$`Fuik 4 - M1`)
              |!is.na(Afvangsten$`Fuik 5 - M1`)
              |!is.na(Afvangsten$`Fuik 6 - M1`)
              |!is.na(Afvangsten$`Fuik 7 - M1`)
              |!is.na(Afvangsten$`Fuik 8 - M1`)
              |!is.na(Afvangsten$`Fuik 9 - M1`)
              |!is.na(Afvangsten$`Fuik 10 - M1`)
              |!is.na(Afvangsten$`Fuik 11 - M1`)
              |!is.na(Afvangsten$`Fuik 12 - M1`)] <- 
  rowSums(Afvangsten[!is.na(Afvangsten$`Fuik 1 - M1`)
                     |!is.na(Afvangsten$`Fuik 2 - M1`)
                     |!is.na(Afvangsten$`Fuik 3 - M1`)
                     |!is.na(Afvangsten$`Fuik 4 - M1`)
                     |!is.na(Afvangsten$`Fuik 5 - M1`)
                     |!is.na(Afvangsten$`Fuik 6 - M1`)
                     |!is.na(Afvangsten$`Fuik 7 - M1`)
                     |!is.na(Afvangsten$`Fuik 8 - M1`)
                     |!is.na(Afvangsten$`Fuik 9 - M1`)
                     |!is.na(Afvangsten$`Fuik 10 - M1`)
                     |!is.na(Afvangsten$`Fuik 11 - M1`)
                     |!is.na(Afvangsten$`Fuik 12 - M1`), 
                     c('Fuik 1 - M1', 
                       'Fuik 2 - M1',
                       'Fuik 3 - M1',
                       'Fuik 4 - M1',
                       'Fuik 5 - M1',
                       'Fuik 6 - M1',
                       'Fuik 7 - M1',
                       'Fuik 8 - M1',
                       'Fuik 9 - M1',
                       'Fuik 10 - M1',
                       'Fuik 11 - M1',
                       'Fuik 12 - M1')], 
          na.rm = T)

Afvangsten$M2[!is.na(Afvangsten$`Fuik 1 - M2`)
              |!is.na(Afvangsten$`Fuik 2 - M2`)
              |!is.na(Afvangsten$`Fuik 3 - M2`)
              |!is.na(Afvangsten$`Fuik 4 - M2`)
              |!is.na(Afvangsten$`Fuik 5 - M2`)
              |!is.na(Afvangsten$`Fuik 6 - M2`)
              |!is.na(Afvangsten$`Fuik 7 - M2`)
              |!is.na(Afvangsten$`Fuik 8 - M2`)
              |!is.na(Afvangsten$`Fuik 9 - M2`)
              |!is.na(Afvangsten$`Fuik 10 - M2`)
              |!is.na(Afvangsten$`Fuik 11 - M2`)
              |!is.na(Afvangsten$`Fuik 12 - M2`)] <- 
  rowSums(Afvangsten[!is.na(Afvangsten$`Fuik 1 - M2`)
                     |!is.na(Afvangsten$`Fuik 2 - M2`)
                     |!is.na(Afvangsten$`Fuik 3 - M2`)
                     |!is.na(Afvangsten$`Fuik 4 - M2`)
                     |!is.na(Afvangsten$`Fuik 5 - M2`)
                     |!is.na(Afvangsten$`Fuik 6 - M2`)
                     |!is.na(Afvangsten$`Fuik 7 - M2`)
                     |!is.na(Afvangsten$`Fuik 8 - M2`)
                     |!is.na(Afvangsten$`Fuik 9 - M2`)
                     |!is.na(Afvangsten$`Fuik 10 - M2`)
                     |!is.na(Afvangsten$`Fuik 11 - M2`)
                     |!is.na(Afvangsten$`Fuik 12 - M2`), 
                     c('Fuik 1 - M2', 
                       'Fuik 2 - M2',
                       'Fuik 3 - M2',
                       'Fuik 4 - M2',
                       'Fuik 5 - M2',
                       'Fuik 6 - M2',
                       'Fuik 7 - M2',
                       'Fuik 8 - M2',
                       'Fuik 9 - M2',
                       'Fuik 10 - M2',
                       'Fuik 11 - M2',
                       'Fuik 12 - M2')], 
          na.rm = T)

Afvangsten$AM[!is.na(Afvangsten$`Fuik 1 - AM`)
              |!is.na(Afvangsten$`Fuik 2 - AM`)
              |!is.na(Afvangsten$`Fuik 3 - AM`)
              |!is.na(Afvangsten$`Fuik 4 - AM`)
              |!is.na(Afvangsten$`Fuik 5 - AM`)
              |!is.na(Afvangsten$`Fuik 6 - AM`)
              |!is.na(Afvangsten$`Fuik 7 - AM`)
              |!is.na(Afvangsten$`Fuik 8 - AM`)
              |!is.na(Afvangsten$`Fuik 9 - AM`)
              |!is.na(Afvangsten$`Fuik 10 - AM`)
              |!is.na(Afvangsten$`Fuik 11 - AM`)
              |!is.na(Afvangsten$`Fuik 12 - AM`)] <- 
  rowSums(Afvangsten[!is.na(Afvangsten$`Fuik 1 - AM`)
                     |!is.na(Afvangsten$`Fuik 2 - AM`)
                     |!is.na(Afvangsten$`Fuik 3 - AM`)
                     |!is.na(Afvangsten$`Fuik 4 - AM`)
                     |!is.na(Afvangsten$`Fuik 5 - AM`)
                     |!is.na(Afvangsten$`Fuik 6 - AM`)
                     |!is.na(Afvangsten$`Fuik 7 - AM`)
                     |!is.na(Afvangsten$`Fuik 8 - AM`)
                     |!is.na(Afvangsten$`Fuik 9 - AM`)
                     |!is.na(Afvangsten$`Fuik 10 - AM`)
                     |!is.na(Afvangsten$`Fuik 11 - AM`)
                     |!is.na(Afvangsten$`Fuik 12 - AM`), 
                     c('Fuik 1 - AM', 
                       'Fuik 2 - AM',
                       'Fuik 3 - AM',
                       'Fuik 4 - AM',
                       'Fuik 5 - AM',
                       'Fuik 6 - AM',
                       'Fuik 7 - AM',
                       'Fuik 8 - AM',
                       'Fuik 9 - AM',
                       'Fuik 10 - AM',
                       'Fuik 11 - AM',
                       'Fuik 12 - AM')], 
          na.rm = T)

Afvangsten$AV[!is.na(Afvangsten$`Fuik 1 - AV`)
              |!is.na(Afvangsten$`Fuik 2 - AV`)
              |!is.na(Afvangsten$`Fuik 3 - AV`)
              |!is.na(Afvangsten$`Fuik 4 - AV`)
              |!is.na(Afvangsten$`Fuik 5 - AV`)
              |!is.na(Afvangsten$`Fuik 6 - AV`)
              |!is.na(Afvangsten$`Fuik 7 - AV`)
              |!is.na(Afvangsten$`Fuik 8 - AV`)
              |!is.na(Afvangsten$`Fuik 9 - AV`)
              |!is.na(Afvangsten$`Fuik 10 - AV`)
              |!is.na(Afvangsten$`Fuik 11 - AV`)
              |!is.na(Afvangsten$`Fuik 12 - AV`)] <- 
  rowSums(Afvangsten[!is.na(Afvangsten$`Fuik 1 - AV`)
                     |!is.na(Afvangsten$`Fuik 2 - AV`)
                     |!is.na(Afvangsten$`Fuik 3 - AV`)
                     |!is.na(Afvangsten$`Fuik 4 - AV`)
                     |!is.na(Afvangsten$`Fuik 5 - AV`)
                     |!is.na(Afvangsten$`Fuik 6 - AV`)
                     |!is.na(Afvangsten$`Fuik 7 - AV`)
                     |!is.na(Afvangsten$`Fuik 8 - AV`)
                     |!is.na(Afvangsten$`Fuik 9 - AV`)
                     |!is.na(Afvangsten$`Fuik 10 - AV`)
                     |!is.na(Afvangsten$`Fuik 11 - AV`)
                     |!is.na(Afvangsten$`Fuik 12 - AV`), 
                     c('Fuik 1 - AV', 
                       'Fuik 2 - AV',
                       'Fuik 3 - AV',
                       'Fuik 4 - AV',
                       'Fuik 5 - AV',
                       'Fuik 6 - AV',
                       'Fuik 7 - AV',
                       'Fuik 8 - AV',
                       'Fuik 9 - AV',
                       'Fuik 10 - AV',
                       'Fuik 11 - AV',
                       'Fuik 12 - AV')], 
          na.rm = T)

print(Afvangsten$L00)
print(Afvangsten$L0)
print(Afvangsten$L1)
print(Afvangsten$L2)
print(Afvangsten$M1)
print(Afvangsten$M2)
print(Afvangsten$AM)
print(Afvangsten$AV)
```

```{r Calculate Totals}
#Larvea for CPUE calculation excludes those larvea that are too small (L00)
#Post - Metamorfs (M1, M2, AM, AV) are excluded by default
Afvangsten$Totaal <- NA
Afvangsten$Totaal_Larven.All <- NA
Afvangsten$Totaal_Larven.CPUE <- NA

Afvangsten$Totaal[!is.na(Afvangsten$L00)
                  |!is.na(Afvangsten$L0)
                  |!is.na(Afvangsten$L1)
                  |!is.na(Afvangsten$L2)
                  |!is.na(Afvangsten$M1)
                  |!is.na(Afvangsten$M2)
                  |!is.na(Afvangsten$AM)
                  |!is.na(Afvangsten$AV)] <- 
  rowSums(Afvangsten[!is.na(Afvangsten$L00)
                     |!is.na(Afvangsten$L0)
                     |!is.na(Afvangsten$L1)
                     |!is.na(Afvangsten$L2)
                     |!is.na(Afvangsten$M1)
                     |!is.na(Afvangsten$M2)
                     |!is.na(Afvangsten$AM)
                     |!is.na(Afvangsten$AV),
                     c('L00',
                       'L0',
                       'L1',
                       'L2',
                       'M1',
                       'M2',
                       'AM',
                       'AV')]
          ,na.rm=T)

Afvangsten$Totaal_Larven.All[!is.na(Afvangsten$L00)
                             |!is.na(Afvangsten$L0)
                             |!is.na(Afvangsten$L1)
                             |!is.na(Afvangsten$L2)] <- 
  rowSums(Afvangsten[!is.na(Afvangsten$L00)
                     |!is.na(Afvangsten$L0)
                     |!is.na(Afvangsten$L1)
                     |!is.na(Afvangsten$L2),
                     c('L00',
                       'L0',
                       'L1',
                       'L2')]
          ,na.rm=T)

Afvangsten$Totaal_Larven.CPUE[!is.na(Afvangsten$L0)
                              |!is.na(Afvangsten$L1)
                              |!is.na(Afvangsten$L2)] <- 
  rowSums(Afvangsten[!is.na(Afvangsten$L0)
                     |!is.na(Afvangsten$L1)
                     |!is.na(Afvangsten$L2),
                     c('L0',
                       'L1',
                       'L2')]
          ,na.rm=T)

Afvangsten$Totaal_Larven.CPUE <- ifelse(is.na(Afvangsten$Totaal_Larven.CPUE),0, Afvangsten$Totaal_Larven.CPUE)
print(Afvangsten$Totaal)
print(Afvangsten$Totaal_Larven.All)
print(Afvangsten$Totaal_Larven.CPUE)
Afvangsten$`Aantal fuiken (Totaal)` <- as.numeric(Afvangsten$`Aantal fuiken (Totaal)`)
table(Afvangsten$`Aantal fuiken (Totaal)`, useNA = "always")
```

```{r Calculate CPUE}
#CPUE = Catch per unit of effort.
#Unit of effort = 1 fyke per 24 hours* 
#Catch = total of larvea for CPUE calculation
#*Data is as such that every 24h a number of fykes are used a record is made
Afvangsten$CPUE <- Afvangsten$Totaal_Larven.CPUE/Afvangsten$`Aantal fuiken (Totaal)`
print(Afvangsten$CPUE)

```
```{r set up directories}
if(!dir.exists("./Output/Afbeeldingen/")){
  dir.create("./Output/Afbeeldingen/")
}

if(!dir.exists("./Output/Overviews/")){
  dir.create("./Output/Overviews/")
}
```

```{r Selecteer brondata voor grafieken}
GRA_Brondata <- Afvangsten[c("Datum", "Location", "L00", "L0", "L1", "L2", "M1", "M2", "AM", "AV", "Totaal", "Totaal_Larven.All", "Totaal_Larven.CPUE","Aantal fuiken (Totaal)","CPUE")]

GRA_Brondata_Long <- GRA_Brondata %>% 
  select(-Totaal, -Totaal_Larven.All, -Totaal_Larven.CPUE, -`Aantal fuiken (Totaal)`, -CPUE) %>% 
  gather(Stadium,n, -Datum, -Location) %>% 
  mutate(n = case_when(is.na(n) ~ 0,
                       TRUE ~ n),
         Jaar = lubridate::year(Datum),
         Maand = lubridate::month(Datum)) %>% 
  group_by(Location, Jaar, Maand, Stadium) %>% 
  summarise(n = sum(n))


table(GRA_Brondata_Long$Stadium, useNA = "ifany")
table(GRA_Brondata_Long$Jaar, useNA = "ifany")
```

```{r Datums juist zetten}
#GRA_Brondata$Datum <- as.Date(GRA_Brondata$Datum, format = "%d-%m-%Y")
GRA_Brondata$Jaar <- lubridate::year(GRA_Brondata$Datum)
GRA_Brondata$Maand <- lubridate::month(GRA_Brondata$Datum)
GRA_Brondata$Dag <- lubridate::day(GRA_Brondata$Datum)
GRA_Brondata$Datum2 <- paste0(GRA_Brondata$Dag, "-",GRA_Brondata$Maand)
#GRA_Brondata$Datum <- as.factor(format(GRA_Brondata$Datum, format='%m-%d'))

GRA_Brondata <- GRA_Brondata %>% 
  group_by(Datum, Location, Jaar, Maand, Dag) %>% 
  summarise(L00 = sum(L00), 
            L0 = sum(L0), 
            L1 = sum(L1), 
            L2 = sum(L2), 
            M1 = sum(M1), 
            M2 = sum(M2), 
            AM = sum(AM), 
            AV = sum(AV),
            Totaal = sum(Totaal),
            Totaal_Larven.All = sum(Totaal_Larven.All),
            Totaal_Larven.CPUE = sum(Totaal_Larven.CPUE),
            `Aantal fuiken (Totaal)` = sum(`Aantal fuiken (Totaal)`),
            CPUE = sum(CPUE),
            n = n())
```

```{r CPUE/dag per jaar}
Jaren <- unique(GRA_Brondata$Jaar)
temp <- GRA_Brondata %>% 
  group_by(Location) %>% 
  arrange(Datum, .by_group = TRUE)

for(j in Jaren){
  #Subset years
  temp2 <- subset(temp, Jaar == j)
  Locations <- unique(temp2$Location)
  for(i in Locations){
    #Create dynamic texts
    i2 <- gsub(i, pattern = " ", replacement = "")
    path <- paste("./Output/Afbeeldingen/", i2, sep="")
    dir.create(path)
    fNaam <- paste(i,"CPUE", j, sep="_")
    fNaam <- paste(fNaam, ".jpeg", sep="")
    #subset locations
    temp3 <- subset(temp2, Location == i )
    #Create plot
    labels <- strftime(x = temp3$Datum, "%d-%b")
    plot <- ggplot(temp3, aes(x=as.character.Date(Datum), y=CPUE)) + 
      geom_bar(stat="identity", aes(fill="red"))
    plot <- plot + ggtitle(paste("Vangst per eenheid van inspanning:", i, " ", j))
    plot <- plot + expand_limits(x = 0, y = 0)
    plot <- plot + scale_x_discrete(expand = c(0, 0), labels = labels) + scale_y_continuous(limits=c(0,NA),expand = c(0, 0))
    plot <- plot + theme(legend.position="none")
    plot <- plot + theme(axis.line = element_line(color="black", size = 0.5))
    plot <- plot + xlab("Datum")
    plot <- plot + ylab("CPUE")
    #Calculate dynamic dimensions
    width <- ifelse(nrow(temp3)<13, 20, (nrow(temp3)*2))
    height<- ifelse(nrow(temp3)<13, 8, (nrow(temp3)*1))
    print(paste("CPUE", i, j, sep=" "))
    print(path)
    print(paste("w:",width))
    print(paste("h:",height))
    #Export file
    ggsave(filename = fNaam, path = path, width=width, height=height, units = c("cm"), dpi = 300)
  }
}
```

```{r absoluut/dag/jaar}

GRA_Brondata %>% gather(Stage, Aantal, L00:AV) -> tempgather

Jaren <- unique(GRA_Brondata$Jaar)

for(j in Jaren){
  temp2 <- subset(GRA_Brondata, Jaar == j)
  Locations <- unique(temp2$Location)
  for(i in Locations){
    #Create dynamic texts
    i2 <- gsub(i, pattern = " ", replacement = "")
    path <- paste("./Output/Afbeeldingen/", i2, sep="")
    dir.create(path)
    fNaam <- paste(i ,"TOT", j, sep="_")
    fNaam <- paste(fNaam, ".jpeg", sep = "")
    #subset locations
    temp3 <- subset(temp2, Location == i )
    #Create plot
    labels <- strftime(x = temp3$Datum, "%d-%b")
    plot <- ggplot(temp3, aes(x=as.character.Date(Datum), y=Totaal)) + geom_bar(stat="identity")
    plot <- plot + ggtitle(paste("Absolute vangsten:", i, " ", j))
    plot <- plot + expand_limits(x = 0, y = 0)
    plot <- plot + scale_x_discrete(expand = c(0, 0), labels = labels) + scale_y_continuous(limits=c(0,NA),expand = c(0, 0))
    plot <- plot + theme(legend.position="none")
    plot <- plot + xlab("Datum")
    plot <- plot + ylab("Totaal")
    print(plot)
    #Calculate dynamic dimensions
    width <- ifelse(nrow(temp3)<13, 20, (nrow(temp3)*2))
    height<- ifelse(nrow(temp3)<13, 8, (nrow(temp3)*1))
    print(paste("TOT", i, j, sep=" "))
    print(path)
    print(paste("w:",width))
    print(paste("h:",height))
    #Export file
    ggsave(filename = fNaam, path = path, width=width, height=height, units = c("cm"), dpi = 300, limitsize = F)
  }
}
```

```{r CPUE all years}
temp <- GRA_Brondata
Locations <- unique(temp$Location)

temp2 <-  temp %>% 
  group_by(Location, Jaar, Maand) %>% 
  summarise(meanCPUE = mean(CPUE, na.rm = TRUE), sd = sd(CPUE))

for(i in Locations){
  temp3 <- subset(temp, Location == i )
  o <- n_distinct(temp3$Jaar)
  if(o > 1){
    #Create dynamic texts
    i2 <- gsub(i, pattern = " ", replacement = "")
    path <- paste("./Output/Afbeeldingen/", i2, sep="")
    dir.create(path)
    jmax <- max(temp3$Jaar)
    jmin <- min(temp3$Jaar)
    fNaam <- paste(i,"CPUE",jmin, jmax, sep="_")
    fNaam <- paste(fNaam, ".jpeg", sep="")
    #Create plot data
    temp3 <- temp3 %>% 
      group_by(Jaar) %>% 
      arrange(Maand) %>% 
      mutate(Maand = factor(Maand, levels = c("4","5","6","7","8","9","10")))
    #Calculate units of effort
    temp3_UE <- temp3 %>% 
      group_by(Jaar) %>% 
      summarise(UE = sum(`Aantal fuiken (Totaal)`), avg = round(mean(CPUE), 2), sd = round(sd(CPUE), 2))
    
    #Merge datasets
    temp3 <- temp3 %>% 
      left_join(temp3_UE) %>% 
      mutate(Jaar_UE = paste0(Jaar, " (UE= ", UE, " fuikdagen, Gem. CPUE= ", avg, " +-", sd, ")"))
    
    plot <- ggplot(temp3, aes(x=Maand, y=CPUE)) + 
      geom_boxplot()
    plot <- plot + ggtitle(paste("Vangst per eenheid van inspanning:", i, " ", jmin, "-", jmax))
    plot <- plot + expand_limits(x = 4, y = 0)
    plot <- plot + scale_x_discrete(expand = c(0, 0), labels = c("4" = "Apr", "5" = "Mei","6" = "Jun",  "7" = "Jul", "8" = "Aug", "9" = "Sep","10" = "Okt")) 
    plot <- plot + scale_y_continuous(expand = expand_scale(add = c(0, 5)))
    plot <- plot + theme(legend.position="none")
    plot <- plot + theme(axis.line = element_line(color="black", size = 1))
    plot <- plot + xlab("Maand")
    plot <- plot + ylab("CPUE")
    plot <- plot + facet_wrap(~Jaar_UE, scales = "fixed", nrow = o)
    #Calculate dynamic dimensions
    width <- 25
    height<- o*6
    print(paste("CPUE", i, jmin, jmax, sep=" "))
    print(path)
    print(paste("w:",width))
    print(paste("h:",height))
    #Export file
    ggsave(filename = fNaam, path = path, width=width, height=height, units = c("cm"), dpi = 300, limitsize = F)
  }
  else{
    print(paste(i, "heeft slechts 1 jaar data"))
  }
}
```

```{r absoluut alle jaren}
temp <- GRA_Brondata
Locations <- unique(temp$Location)

temp2 <-  temp %>% 
  group_by(Location, Jaar, Maand) %>% 
  summarise(meanTotaal = mean(Totaal, na.rm = TRUE), sd = sd(Totaal))

for(i in Locations){
  temp3 <- subset(temp, Location == i )
  o <- n_distinct(temp3$Jaar)
  if(o > 1){
    #Create dynamic texts
    i2 <- gsub(i, pattern = " ", replacement = "")
    path <- paste("./Output/Afbeeldingen/", i2, sep="")
    dir.create(path)
    jmax <- max(temp3$Jaar)
    jmin <- min(temp3$Jaar)
    fNaam <- paste(i ,"TOT",jmin, jmax, sep="_")
    fNaam <- paste(fNaam, ".jpeg", sep = "")
    #Create plot
    temp3 <- temp3 %>% 
      group_by(Jaar) %>% 
      arrange(Maand) %>% 
      mutate(Maand = factor(Maand, levels = c("4","5","6","7","8","9","10")))
    
    plot <- ggplot(temp3, aes(x=Maand, y=Totaal)) + 
      geom_boxplot(stat = "boxplot")
    plot <- plot + ggtitle(paste("Absolute vangsten:", i, " ", jmin, "-", jmax))
    plot <- plot + expand_limits(x = 0, y = 0)
    plot <- plot + scale_x_discrete(expand = c(0, 0), labels = c("4" = "Apr", "5" = "Mei","6" = "Jun",  "7" = "Jul", "8" = "Aug", "9" = "Sep","10" = "Okt"))  
    plot <- plot + scale_y_continuous(limits=c(0,NA),expand = expand_scale(add = c(0, 5)))
    plot <- plot + theme(legend.position="none")
    plot <- plot + theme(axis.line = element_line(color="black", size = 1))
    plot <- plot + xlab("Datum")
    plot <- plot + ylab("Absolute vangst")
    plot <- plot + facet_wrap(~Jaar, scales = "fixed", nrow = o)
    #Calculate dynamic dimensions
    width <- 25
    height<- o*6
    print(paste("CPUE", i, jmin, jmax, sep=" "))
    print(path)
    print(paste("w:",width))
    print(paste("h:",height))
    #Export file
    ggsave(filename = fNaam, path = path, width=width, height=height, units = c("cm"), dpi = 300, limitsize = F)
  }
  else{
    print(paste(i, "heeft slechts 1 jaar data"))}
}

```

```{r GSL alle jaren}
temp <- GRA_Brondata
Locations <- unique(temp$Location)
Jaren <- unique(temp$Jaar)

temp3 <- data.frame()

p <- 1
for(j in Jaren){
  temp2 <- subset(temp, Jaar == j)
  Locations <- unique(temp2$Location)
  for(l in Locations){
    temp2A <- subset(temp2, Location == l)
    t <- nrow(temp2A)
    for(i in 1:nrow(temp2A)){
      if(i == 1){
        temp2A$GSL[i] <- temp2A$CPUE[i]*26
      }else{
        if(i == 2){
          temp2A$GSL[i] <- ((temp2A$CPUE[i-1] + temp2A$CPUE[i])/2)*26
        }else{
          temp2A$GSL[i] <- ((temp2A$CPUE[i-1] + temp2A$CPUE[i] + temp2A$CPUE[i-2])/3)*26
        }
      }
      temp2A <- temp2A %>% 
        arrange(Datum) %>% 
        ungroup()
      t <- nrow(temp2A)
      if(p < i){
        p <- i+1
      }else{
        p <- i
      }
      temp2A$Remainder[i] <- sum(temp2A$Totaal_Larven.CPUE[p:t],na.rm =F)
      temp2A$Error[i] <- temp2A$Remainder[i]-temp2A$GSL[i]
    }
    temp3 <- rbind(temp2A, temp3)
  }
  
}

Jaren <- unique(temp3$Jaar)

for(j in Jaren){
  temp4 <- subset(temp3, Jaar == j)
  Locations <- unique(temp4$Location)
  for(l in Locations){
    #Create dynamic texts
    i2 <- gsub(l, pattern = " ", replacement = "")
    path <- paste("./Output/Afbeeldingen/", i2, sep="")
    dir.create(path)
    fNaam <- paste(l ,"GSL", j, sep="_")
    fNaam <- paste(fNaam, ".jpeg", sep = "")
    #subset locations
    temp5 <- temp4 %>% 
      filter(Location == l) %>% 
      arrange(Datum)
    #Create plot
    labels <- strftime(x = temp5$Datum, "%d-%b")
    temp6 <- temp5 %>% 
      filter(GSL <= 100)
    temp7 <- temp5 %>% 
      filter(GSL <= 10)
    temp8 <- temp5 %>% 
      filter(Error > 0.5 * GSL)
    temp9 <- temp5 %>% 
      filter(Error < -0.5 * GSL)
    
    plot <- ggplot(temp5, aes(x=as.character.Date(Datum), y=GSL)) + 
      geom_bar(stat="identity", fill = "blue") + 
      geom_bar(data = temp6, mapping = aes(x=as.character.Date(Datum), y=GSL), stat = "identity", fill = "yellow") +
      geom_bar(data = temp7, mapping = aes(x=as.character.Date(Datum), y=GSL), stat = "identity", fill = "green") +
      geom_bar(data = temp9, mapping = aes(x=as.character.Date(Datum), y=GSL), stat = "identity", fill = "orange") +
      geom_bar(data = temp8, mapping = aes(x=as.character.Date(Datum), y=GSL), stat = "identity", fill = "red")
    plot <- plot + ggtitle(paste("Geschat startaantal larven:", l, " ", j))
    plot <- plot + expand_limits(x = 0, y = 0)
    plot <- plot + scale_x_discrete(expand = c(0, 0), labels = labels) 
    plot <- plot + scale_y_continuous(limits=c(0,NA),expand = c(0, 0))
    plot <- plot + theme(legend.position="none")
    plot <- plot + xlab("Datum")
    plot <- plot + ylab("GSL")
    plot <- plot + geom_hline(yintercept = 100, linetype = "dashed", color = "red")
    plot <- plot + geom_hline(yintercept = 10, linetype = "dashed", color = "green")
    plot <- plot + geom_errorbar(aes(ymin = GSL, ymax = GSL + Error), width=.1)
    print(plot)
    #Calculate dynamic dimensions
    width <- ifelse(nrow(temp5)<13, 20, (nrow(temp5)*1.5))
    height<- ifelse(nrow(temp5)<13, 5, (nrow(temp5)*1))
    print(paste("GSL", l, j, sep=" "))
    print(path)
    print(paste("w:",width))
    print(paste("h:",height))
    #Export file
    ggsave(filename = fNaam, path = path, width=width, height=height, units = c("cm"), dpi = 300, limitsize = F)
  }
}
```

```{r Arendonk Overview, fig.width=10, eval=FALSE}
font.add("Kievit", "./Fonts/KievitOT-Light2.otf")
showtext.auto()

file_extensions <- c(".jpeg", ".eps")

color1 <- rgb(red = 194, green = 14, blue = 26, maxColorValue = 255)
color2 <- rgb(red = 234, green = 184, blue = 24, maxColorValue = 255)
color3 <- rgb(red = 0, green = 158, blue = 224, maxColorValue = 255)
color4 <- rgb(116,125,132,maxColorValue = 255)
color5 <- rgb(213,215,212, maxColorValue = 255, alpha = 75)

Arendonk_Overview_Data <- Afvangsten %>% 
  dplyr::select(Locatie, Location, Jaar, Totaal_Larven.All, Totaal_Larven.CPUE, Totaal) %>% 
  filter(Locatie == "Arendonk" & !grepl("visput", Location) & !grepl("b", Location)) %>% 
  mutate(`(Jong)Volwassen` = Totaal - Totaal_Larven.All,
         Larven = Totaal_Larven.CPUE,
         `Kleinste Larven` = Totaal_Larven.All - Totaal_Larven.CPUE) %>% 
  dplyr::select(-Totaal, -Totaal_Larven.All, -Totaal_Larven.CPUE) %>% 
  gather(key = type, value = aantal, -Locatie, -Location, -Jaar) %>% 
  group_by(Jaar, Location, type) %>% 
  summarise(Totale_vangst = sum(aantal, na.rm = TRUE)) %>% 
  arrange(Jaar, Totale_vangst)

plot <- ggplot(Arendonk_Overview_Data, aes(x = Jaar, y= Totale_vangst, fill = type)) +
  geom_col(position = "stack") +
  scale_fill_manual(values = c(color1, color2, color3)) +
  facet_grid(.~Location) +
  ylab("Aantal gevangen stierkikkers") +
  scale_y_continuous(limits=c(0,NA),expand = c(0, 0)) +
  theme(text=element_text(family = "Kievit", size = 50)) +
  theme(legend.position = "bottom", legend.title = element_blank()) +
  theme(strip.background = element_rect(fill = color4),
        panel.background = element_rect(fill = color5)) +
  theme(axis.text = element_text(color = color4),
        legend.text = element_text(color = color4)) +
  theme(axis.line.x.bottom = element_line(color = "black"),
        axis.line.y.left = element_line(color = "black"))

for(e in file_extensions){
  fn <- paste0("./Output/Overviews/Arendonk_Overview", e)
  ggsave(fn, plot, width = 10)
}

print(plot)
```

```{r graph per stadium}
Locations <- unique(GRA_Brondata_Long$Location)

for(l in Locations){
  temp <- GRA_Brondata_Long %>% 
    filter(Location == l)
  jaren <- unique(temp$Jaar)
  for(j in jaren){
    temp2 <- temp %>% 
      filter(Jaar == j)
    i2 <- gsub(l, pattern = " ", replacement = "")
    path <- paste("./Output/Afbeeldingen/", i2, sep="")
    dir.create(path)
    fNaam <- paste(l ,"Vangst_per_Stadium", j, sep="_")
    fNaam <- paste(fNaam, ".jpeg", sep = "")
    p <- ggplot(temp2, aes(x = as.factor(Maand), y = n, fill = Stadium)) +
      geom_bar(position = "stack", stat = "identity") +
      xlab("Maand") + 
      ylab("Absolute vangsten") +
      ggtitle(label = "Vangst per stadium",
              subtitle = paste(l, "-", j))
    ggsave(filename = fNaam, path = path, width=10, height=10, units = c("cm"), dpi = 300, limitsize = F)
  }
}

```

